"""Bake the bundled handwriting atlas. Requires Pillow 12.1.1; runtime does not."""

from pathlib import Path
import hashlib
import urllib.request
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
CACHE = ROOT / "build" / "font"
SOURCE = "https://raw.githubusercontent.com/google/fonts/aeb9574d3cb4ab2ac5de70a8c730b11662281803/ofl/patrickhand/"
SHA256 = "0f173b3e6cb6d1af25babf7f0057c5ac4ee11f9992b0469bb817e967ef4ad0fc"


def main():
    CACHE.mkdir(parents=True, exist_ok=True)
    source = CACHE / "PatrickHand-Regular.ttf"
    if not source.exists():
        source.write_bytes(urllib.request.urlopen(SOURCE + source.name).read())
    if hashlib.sha256(source.read_bytes()).hexdigest() != SHA256:
        raise RuntimeError("Font checksum mismatch")
    destination = ROOT / "assets" / "fonts"
    destination.mkdir(parents=True, exist_ok=True)
    license_path = destination / "OFL.txt"
    if not license_path.exists():
        license_path.write_bytes(urllib.request.urlopen(SOURCE + "OFL.txt").read())
    font = ImageFont.truetype(str(source), 48)
    atlas = Image.new("RGB", (1024, 512))
    draw = ImageDraw.Draw(atlas)
    advances = []
    for index, code in enumerate(range(32, 127)):
        character = chr(code)
        left, top, right, bottom = font.getbbox(character, anchor="ls")
        if left + 8 < 2 or right + 8 > 62 or top + 60 < 2 or bottom + 60 > 78:
            raise RuntimeError(f"Glyph {character!r} exceeds its padded atlas cell")
        draw.text(
            ((index % 16) * 64 + 8, (index // 16) * 80 + 60),
            character,
            font=font,
            fill="white",
            anchor="ls",
        )
        advances.append(round(font.getlength(character) * 64))
    atlas.save(destination / "handwriting.bmp")
    rows = [", ".join(str(n) for n in advances[i : i + 12]) for i in range(0, 95, 12)]
    header = "// Generated by scripts/generate-font.py from Patrick Hand (SIL OFL 1.1).\n"
    header += "#pragma once\n#include <array>\nnamespace FontMetrics {\n"
    header += "inline constexpr std::array<unsigned short, 95> advances{{\n    "
    header += ",\n    ".join(rows) + "\n}};\n}\n"
    (ROOT / "src" / "utils" / "FontMetrics.h").write_text(header, encoding="utf-8")
    print("Generated handwriting atlas and glyph metrics.")


if __name__ == "__main__":
    main()
